default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("DATABASE_URL", "postgres://jewelryapp:gnldjewelry@1@localhost:5433/jewelryappdb") %>

development:
  <<: *default
  database: jewelry_stock_development

test:
  <<: *default
  database: jewelry_stock_test

production:
  <<: *default
  database: jewelry_stock_production
